baseurl = "https://kubeci.io"
title = "KubeCI"
languageCode = "en-us"
theme = "elate"

[params]

  custom_css = ["css/kubeci.css"]

  author = "Loodse GmbH"
  description = "KubeCI is a Continuous Delivery platform built on Drone for Kubernetes, written in Go"
  email = ""

  [params.navigation]
    brand = "KubeCI"
    home = "Home"
    work = "Plugins"
    # testimonials = "Testimonials"
    services = "Features"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Cloud Native Continuous Delivery."
    subtitle = 'KubeCI is a Continuous Delivery platform built on <a href="https://drone.io">Drone</a> for <a href="https://kubernetes.io">Kubernetes</a> , written in <a href="https://golang.org">Go</a>.'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Develop"
    description = "Developers don't need to setup anything, just commit & push their changes."
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Test"
    description = "Your changes are tested and built inside Pods (Containers) running inside Kubernetes."
    icon = "icon-speedometer"
    img = "img_10.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Deploy your application's containers to any Kubernetes cluster you choose."
    icon = "icon-rocket"
    img = "img_10.jpg"

  # [params.intro.video]
  #   enable = true
  #   title = "Watch the video"
  #   icon = "icon-play2"
  #   url = "https://vimeo.com/channels/staffpicks/93951774"

  # Work section
  [params.work]
    enable = true
    title = "Plugins"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = ''

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"

  # Services section
  [params.services]
    enable = true
    title = "Features"
    description = "KubeCI enables you to go completly cloud native with your CI/CD pipeline."

    [[params.services.item]]
      title = "Shared Cluster"
      description = "No additional infrastructure is required for your CI/CD pipeline, KubeCI can run in the same cluster as your applications."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Supports any language"
      description = "By using containers for each step in your process you can leverage the languages you need without having to use different CI/CD systems."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Simple Configuration"
      description = "KubeCI uses a YAML file stored in the same repository as your code, making it simple to reproduce your builds and for developers to make configuration changes easily"
      icon = "icon-video2"

    [[params.services.item]]
      title = "Unlimited Flexibility"
      description = "Run your builds, tests, and any other steps you can think of simply by using any container with the tools you need, giving you unlimited freedom to cusomize your CI/CD process to suit your needs"
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "These people make KubeCI possible. In case you want to get in touch you can also find them on other platforms."

    [[params.about.item]]
      name = "Sebastian Scheele"
      position = "Loodse CEO"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "https://0.gravatar.com/avatar/2092f7a5f0eedcb3b32a0285d359b8d4?s=300&d=mm"
      alt = "Person3"
      social = [
        ["icon-twitter", "https://twitter.com/HrScheele"],
        ["icon-github", "https://github.com/scheeles"],
      ]

    [[params.about.item]]
      name = "Matthias Loibl"
      position = "Engineer for KubeCI"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "https://0.gravatar.com/avatar/915d80f0d9b6678fad4d1ab36dfc8960?s=300&d=mm"
      alt = "Person1"
      social = [
        ["icon-twitter", "https://twitter.com/metalmatze"],
        ["icon-github", "https://github.com/metalmatze"],
      ]

    [[params.about.item]]
      name = "Brad Rydzewski"
      position = "Creator of Drone"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "https://0.gravatar.com/avatar/8c58a0be77ee441bb8f8595b7f1b4e87?s=300&d=mm"
      alt = "Person2"
      social = [
        ["icon-twitter", "https://twitter.com/bradrydzewski"],
        ["icon-github", "https://github.com/bradrydzewski"]
      ]


  # # Counters section
  # [params.counters]
  #   enable = true
  #   title = "Stats"
  #   background = "full_image_1.jpg"

  #   [[params.counters.item]]
  #     description = "Finished projects"
  #     icon = "icon-briefcase"
  #     from = 0
  #     to = 89
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Lines of code"
  #     icon = "icon-code"
  #     from = 0
  #     to = 2343409
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Cups of coffee"
  #     icon = "icon-cup"
  #     from = 0
  #     to = 1302
  #     interval = 50
  #     speed = 5000

  #   [[params.counters.item]]
  #     description = "Happy clients"
  #     icon = "icon-people"
  #     from = 0
  #     to = 52
  #     interval = 50
  #     speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    title = "Get in touch"
    description = "<a href='https://loodse.com'>Loodse</a> provides a wide range of consulting services tailor-made to your needs. We support your teams ability to build, implement and automate distributed, container-based and cloud native infrastructure. In close cooperation with your team, our experts will help you avoid common pitfalls, while minimizing time to market and building a high level of in-house competence and institutional knowledge."

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Fuhlsbüttler Straße 405<br> 22307 Hamburg"],
        ["icon-phone", "+49 (40) 60 590 7110"],
        ["icon-envelope", "info@loodse.com"],
        ["icon-globe", '<a href="https://loodse.com/" target="_blank">loodse.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; <a href="https://loodse.com">Loodse GmbH</a>'
